# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\x12\x06plugin\"}\n\x10\x43onfigureRequest\x12\x38\n\x08settings\x18\x01 \x03(\x0b\x32&.plugin.ConfigureRequest.SettingsEntry\x1a/\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x11\x43onfigureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"1\n\x0b\x43\x61llRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x1e\n\x0c\x43\x61llResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\'\n\x12GetToolInfoRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\"5\n\x13GetToolInfoResponse\x12\x1e\n\x04tool\x18\x01 \x01(\x0b\x32\x10.plugin.ToolInfo\"\x12\n\x10ListToolsRequest\"4\n\x11ListToolsResponse\x12\x1f\n\x05tools\x18\x01 \x03(\x0b\x32\x10.plugin.ToolInfo\"^\n\x08ToolInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0bschema_json\x18\x03 \x01(\t\x12\x1a\n\x12output_schema_json\x18\x04 \x01(\t2\x8b\x02\n\nToolPlugin\x12@\n\tConfigure\x12\x18.plugin.ConfigureRequest\x1a\x19.plugin.ConfigureResponse\x12\x31\n\x04\x43\x61ll\x12\x13.plugin.CallRequest\x1a\x14.plugin.CallResponse\x12\x46\n\x0bGetToolInfo\x12\x1a.plugin.GetToolInfoRequest\x1a\x1b.plugin.GetToolInfoResponse\x12@\n\tListTools\x12\x18.plugin.ListToolsRequest\x1a\x19.plugin.ListToolsResponseB\x14Z\x12squad/plugin/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022squad/plugin/proto'
  _globals['_CONFIGUREREQUEST_SETTINGSENTRY']._loaded_options = None
  _globals['_CONFIGUREREQUEST_SETTINGSENTRY']._serialized_options = b'8\001'
  _globals['_CONFIGUREREQUEST']._serialized_start=24
  _globals['_CONFIGUREREQUEST']._serialized_end=149
  _globals['_CONFIGUREREQUEST_SETTINGSENTRY']._serialized_start=102
  _globals['_CONFIGUREREQUEST_SETTINGSENTRY']._serialized_end=149
  _globals['_CONFIGURERESPONSE']._serialized_start=151
  _globals['_CONFIGURERESPONSE']._serialized_end=202
  _globals['_CALLREQUEST']._serialized_start=204
  _globals['_CALLREQUEST']._serialized_end=253
  _globals['_CALLRESPONSE']._serialized_start=255
  _globals['_CALLRESPONSE']._serialized_end=285
  _globals['_GETTOOLINFOREQUEST']._serialized_start=287
  _globals['_GETTOOLINFOREQUEST']._serialized_end=326
  _globals['_GETTOOLINFORESPONSE']._serialized_start=328
  _globals['_GETTOOLINFORESPONSE']._serialized_end=381
  _globals['_LISTTOOLSREQUEST']._serialized_start=383
  _globals['_LISTTOOLSREQUEST']._serialized_end=401
  _globals['_LISTTOOLSRESPONSE']._serialized_start=403
  _globals['_LISTTOOLSRESPONSE']._serialized_end=455
  _globals['_TOOLINFO']._serialized_start=457
  _globals['_TOOLINFO']._serialized_end=551
  _globals['_TOOLPLUGIN']._serialized_start=554
  _globals['_TOOLPLUGIN']._serialized_end=821
# @@protoc_insertion_point(module_scope)
