# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: plugin.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import plugin_pb2


class ToolPluginBase(abc.ABC):

    @abc.abstractmethod
    async def Configure(self, stream: 'grpclib.server.Stream[plugin_pb2.ConfigureRequest, plugin_pb2.ConfigureResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Call(self, stream: 'grpclib.server.Stream[plugin_pb2.CallRequest, plugin_pb2.CallResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetToolInfo(self, stream: 'grpclib.server.Stream[plugin_pb2.GetToolInfoRequest, plugin_pb2.GetToolInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ListTools(self, stream: 'grpclib.server.Stream[plugin_pb2.ListToolsRequest, plugin_pb2.ListToolsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/plugin.ToolPlugin/Configure': grpclib.const.Handler(
                self.Configure,
                grpclib.const.Cardinality.UNARY_UNARY,
                plugin_pb2.ConfigureRequest,
                plugin_pb2.ConfigureResponse,
            ),
            '/plugin.ToolPlugin/Call': grpclib.const.Handler(
                self.Call,
                grpclib.const.Cardinality.UNARY_UNARY,
                plugin_pb2.CallRequest,
                plugin_pb2.CallResponse,
            ),
            '/plugin.ToolPlugin/GetToolInfo': grpclib.const.Handler(
                self.GetToolInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                plugin_pb2.GetToolInfoRequest,
                plugin_pb2.GetToolInfoResponse,
            ),
            '/plugin.ToolPlugin/ListTools': grpclib.const.Handler(
                self.ListTools,
                grpclib.const.Cardinality.UNARY_UNARY,
                plugin_pb2.ListToolsRequest,
                plugin_pb2.ListToolsResponse,
            ),
        }


class ToolPluginStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Configure = grpclib.client.UnaryUnaryMethod(
            channel,
            '/plugin.ToolPlugin/Configure',
            plugin_pb2.ConfigureRequest,
            plugin_pb2.ConfigureResponse,
        )
        self.Call = grpclib.client.UnaryUnaryMethod(
            channel,
            '/plugin.ToolPlugin/Call',
            plugin_pb2.CallRequest,
            plugin_pb2.CallResponse,
        )
        self.GetToolInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/plugin.ToolPlugin/GetToolInfo',
            plugin_pb2.GetToolInfoRequest,
            plugin_pb2.GetToolInfoResponse,
        )
        self.ListTools = grpclib.client.UnaryUnaryMethod(
            channel,
            '/plugin.ToolPlugin/ListTools',
            plugin_pb2.ListToolsRequest,
            plugin_pb2.ListToolsResponse,
        )
